services:
  postgres:
    image: postgres:15-alpine
    container_name: pg_gateway
    environment:
      POSTGRES_DB: payment_gateway
      POSTGRES_USER: gateway_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gateway_pass}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gateway_user -d payment_gateway" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gateway_net

  api:
    build:
      context: ./backend
    container_name: gateway_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://gateway_user:${POSTGRES_PASSWORD:-gateway_pass}@postgres:5432/payment_gateway
      PORT: 8000
      TEST_MODE: ${TEST_MODE:-false}
      TEST_PAYMENT_SUCCESS: ${TEST_PAYMENT_SUCCESS:-true}
      TEST_PROCESSING_DELAY: ${TEST_PROCESSING_DELAY:-1000}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gateway_pass}
      REDIS_URL: redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - gateway_net

  redis:
    image: redis:7-alpine
    container_name: redis_gateway
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - gateway_net

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    container_name: gateway_worker
    environment:
      DATABASE_URL: postgresql://gateway_user:${POSTGRES_PASSWORD:-gateway_pass}@postgres:5432/payment_gateway
      REDIS_URL: redis://redis:6379
      TEST_MODE: ${TEST_MODE:-false}
      TEST_PAYMENT_SUCCESS: ${TEST_PAYMENT_SUCCESS:-true}
      TEST_PROCESSING_DELAY: ${TEST_PROCESSING_DELAY:-1000}
      WEBHOOK_RETRY_INTERVALS_TEST: ${WEBHOOK_RETRY_INTERVALS_TEST:-false}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      api:
        condition: service_healthy
    networks:
      - gateway_net

  dashboard:
    build:
      context: ./frontend
    container_name: gateway_dashboard
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - gateway_net

  checkout:
    build:
      context: .
      dockerfile: checkout-page/Dockerfile
    container_name: gateway_checkout
    ports:
      - "3001:80"
    depends_on:
      - api
    networks:
      - gateway_net

networks:
  gateway_net:
    driver: bridge
